name: Check rain show point

on:
  workflow_dispatch:
  schedule:
    # https://crontab.guru
    - cron: '55 8 * * *'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest


    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@9db7f66e8e16b5699a514448ce994936c63f0d54
        with:
          deno-version: v1.x

      - name: Run
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          RIDI_USERNAME: ${{ secrets.RIDI_USERNAME }}
          RIDI_PASSWORD: ${{ secrets.RIDI_PASSWORD }}
        run: deno task run
